### PR TITLE
New page button styling

### PR DESCRIPTION
**Pull request by clary149**

### CODE REVIEW

**Review by dqnykamp — COMMENTED** [review]
Much better buttons!  Do you think it would look better with a small margin between them and the menu at the left?

**Review by dqnykamp — COMMENTED** [review]
One more thing, now that I merged #1506 in, can you wrap the bottom button in 

    `if(renderedPages[currentPage-1])`

so that it only shows up after the page is rendered (preventing flashing when the "initializing" message disappears)?  I didn't include that in #1506, as I didn't want to create a merge conflict for this PR.

**Comment by clary149** [comment]
Added margins and additional if statement

**Review by dqnykamp — APPROVED** [review]
Looks good.

**Pull request merged**
