### PR TITLE
valueChanged and immediateValueChanged properties

### LINKED ISSUE #2112: feature request - add public state variable to mathInput, textInput indicating a "blank", "unentered", or "empty" state
for use in cases where feedback or conditionalContent should not be triggered unless the user has already entered a value into the input (where the input is not contained within an answer)

### PR DESCRIPTION
**Pull request by dqnykamp**
Closes #2112

### CODE REVIEW

**Comment by dqnykamp** [comment]
PR is last 2 commits

**Comment by dqnykamp** [comment]
PR is last 3 commits

**Comment by dqnykamp** [comment]
All commits are now part of this PR

**Review by jaltekruse — APPROVED** [review]
+1

**Pull request merged**
