### PR TITLE
Choice input tag styling

### PR DESCRIPTION
**Pull request by keaganeng**
Also removed an unnecessary CSS selector from booleanInput (`button-container`)

### CODE REVIEW

**Comment by keaganeng** [comment]
I committed the on-hover changes Clara suggested on Friday, so this PR is now ready for review!

**Comment by keaganeng** [comment]
Working to resolve issue https://github.com/Doenet/DoenetTools/issues/1636

**Comment by kevincharles** [comment]
Please fix the id's on the choiceinput code. When running the Cypress tests it now fails 12 tests due to the ID not being "_choiceinput1_choice1_input" and similar.  I looked over the code and it wasn't immediately clear where the problem is.

Screen Shot 2022-09-24 at 10 44 17 PM
Screen Shot 2022-09-24 at 10 42 36 PM

**Comment by keaganeng** [comment]
Cypress tests were failing because inputs had a 0x0 dimension. Fixed this issue by making inputs 1x1.

**Review by kevincharles — APPROVED** [review]
Looks great! TY!

**Pull request merged**
