### PR TITLE
Fully featured and defaulted assignment settings

### PR DESCRIPTION
**Pull request by Lyanthropos**

### CODE REVIEW

**Comment by Lyanthropos** [comment]
@clary149 What do you think of the component structure?

**Review by clary149 — APPROVED** [review]
Kevin once said not to add the media folder contents to the gitignore, but if you've already talked to him, the rest of this pr looks good!

**Comment by Lyanthropos** [comment]
Hmmm, I did not. @kevincharles should I remove that?

**Comment by kevincharles** [comment]
Yes, we can't use this until media is not ignored.  We will lose the media files we need.

**Pull request merged**
