### PR TITLE
Previous and Next buttons

### PR DESCRIPTION
**Pull request by Lyanthropos**

### CODE REVIEW

**Comment by Lyanthropos** [comment]
closes #1594

**Comment by dqnykamp** [comment]
I think this is OK for now.  But, having the breadcrumbs, New Attempt, Previous, and Next buttons are together in a row could be hard to visually parse.  I assume any changes would be part of the larger redesign.

**Comment by Lyanthropos** [comment]
Agreed. @kevincharles yet anthoer piece to consider

**Comment by Lyanthropos** [comment]
@kevincharles Do you want cypress tests on this?

**Comment by kevincharles** [comment]
Yes, needs Cypress tests.  Thank you!

**Review by kevincharles — CHANGES_REQUESTED** [review]
Please add Cypress tests. TY!

**Pull request merged**
