### PR TITLE
dontRecurseToShadows replaces shadowDepth in dependencies

### PR DESCRIPTION
**Pull request by dqnykamp**
adjust label

### CODE REVIEW

**Comment by dqnykamp** [comment]
PR is just the last commit

**Review by jaltekruse — APPROVED** [review]
The changes don't include new tests for this fix/feature, but I'll leave it up to you if you want to merge it as is.

**Comment by dqnykamp** [comment]
There are no new tests as this doesn't implement a new feature, just a refactoring under the hood to get the same result in a less complicated way.

**Comment by dqnykamp** [comment]
I suppose one could write a unit test specific to the new implementation, but I haven't been writing such implementation specific tests.

**Pull request merged**
