### PR TITLE
Fix: mailto not working for ref

### LINKED ISSUE #1901: Cannot make a link to a mailto url
A link `<ref uri="mailto:me@doenet.org" >email me</ref>` does not work.

The renderer ref.jsx is looking only for "http" and "https" addresses when creating an external link.

### PR DESCRIPTION
**Pull request by ernzher**
Closes #1901

### CODE REVIEW

**Comment by ernzher** [comment]
Link to issue: https://github.com/Doenet/DoenetTools/issues/1901

**Comment by kevincharles** [comment]
Closes #1901

**Comment by kevincharles** [comment]
Merge conflict.  Please rework.

**Comment by ernzher** [comment]
Due to some complications on my local, created new branch for this fix. New PR: #1971

**Pull request closed without merging**
